---
- hosts: databases
  vars:
    db_packages:
      - mariadb-server
      - MySQL-python
    db_service: mariadb
    src_file: "httpd://materials.example.com/task_control/my.cnf.template"
    dst_file: /etc/my.cnf

  tasks:
  - name: "Install {{ db_packages }} package"
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ db_packages }}"
    notify:
      - start_service

  - name: Download and install {{ dst_file }}
    get_url:
      url: "{{ src_file }}"
      dest: "{{ dst_file }}"
      owner: mysql
      group: mysql
      force: yes
    notify:
      - restart_service
      - set_password

  handlers:
  - name: restart_service
    service:
      name: "{{ db_service }}"
      state: restarted

  - name: set_password
    mysql_user:
      name: root
      password: redhat
...
