---
# tasks file for myvhost

- name: install httpd
  yum:
    name: httpd
    state: latest

- name: start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: true

- name: deliver html content
  copy:
    src: ~/dev-roles/roles/myvhost/files/html/
    dest: '/var/www/vhosts/{{ ansible_hostname }}'

- name: template vhost file
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httd
