---
- hosts: databases
  vars:
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
  - block:
    - name: Check {{ web_package }} installation status
      command: yum list installed "{{ web_package }}"
      register: command_result

    - name: Install {{ web_package }} package
      yum:
        name: "{{ web_package }}"
        state: latest
    
    rescue:
    - name: Install {{ db_package }} package
      yum:
        name: "{{ db_package }}"
        state: latest

    always:
    - name: Start {{ db_service }} service
      service:
        name: "{{ db_service }}"
        state: started
